CREATE TABLE IF NOT EXISTS Bands (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  music_genre VARCHAR(255) NOT NULL,
  responsible VARCHAR(255) UNIQUE NOT NULL 
);

CREATE TABLE IF NOT EXISTS Shows (
  id VARCHAR(255) PRIMARY KEY,
  week_day ENUM("FRIDAY","SATURDAY","SUNDAY"),
  start_time INT NOT NULL,
  end_time INT NOT NULL,
  band_id VARCHAR(255) NOT NULL,
  FOREIGN KEY(band_id) REFERENCES Bands(id)
);

CREATE TABLE IF NOT EXISTS Users (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(255) NOT NULL DEFAULT "NORMAL"
);

CREATE TABLE IF NOT EXISTS Tickets (
id VARCHAR(255) PRIMARY KEY,
name VARCHAR(255) NOT NULL,
ticket_value INT NOT NULL,
ticket_quantity INT NOT NULL,
event_id VARCHAR(255) NOT NULL,
FOREIGN KEY(event_id) REFERENCES Shows(id)
);
